apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
  labels:
    app: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: fabastante/vote:TAG
        ports:
        - containerPort: 80
