apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: roxsross12/votingapp:1.0.0-worker